In [1]:
import numpy as np

In [2]:
m = np.zeros(2 * [3,])

for ij in np.ndindex(m.shape):
    m[ij] = ij[0] + ij[1] * 2

m += m.T
m

array([[ 0.,  3.,  6.],
       [ 3.,  6.,  9.],
       [ 6.,  9., 12.]])

In [3]:
evs, evecs = np.linalg.eigh(m)

evs, evecs

(array([-2.61895004e+00, -3.21059368e-16,  2.06189500e+01]),
 array([[ 0.8598926 ,  0.40824829, -0.30646053],
        [ 0.19382266, -0.81649658, -0.54384383],
        [-0.47224729,  0.40824829, -0.78122713]]))

In [4]:
# verify M |s> = m_s |s> forall s

for ev, v in zip(evs, evecs.T):
    d = m @ v - ev * v
    print(np.linalg.norm(d), d.round(decimals=12))

1.5543122344752192e-15 [0. 0. 0.]
4.7718044982237e-16 [ 0.  0. -0.]
8.379058453350832e-15 [ 0. -0. -0.]


In [5]:
# verify M = \sum_s |s> m_s <s|
# -> M_ij = \sum_s s^i m_s s^j

M = np.zeros_like(m)

for (i, j) in np.ndindex(M.shape):
    tmp = 0
    for s, ev in enumerate(evs):
        # tmp += ev * evecs[i, s] * evecs[j, s]
        tmp += ev * evecs.T[s, i] * evecs.T[s, j]

    M[i, j] = tmp

M.round(0)

array([[-0.,  3.,  6.],
       [ 3.,  6.,  9.],
       [ 6.,  9., 12.]])

In [6]:
# verify M = \sum_s |s> m_s <s|
# M_ij = \sum_s s^i m_s s^j

M = np.zeros_like(m)

for ev, v in zip(evs, evecs.T):
    M += ev * np.outer(v, v)


M.round(0)

array([[-0.,  3.,  6.],
       [ 3.,  6.,  9.],
       [ 6.,  9., 12.]])

In [7]:
evecs.sum(axis=1)

array([ 0.96168036, -1.16651776, -0.84522613])

In [8]:
V = np.arange(3)
V

array([0, 1, 2])

In [9]:
(evecs.T @ evecs).round(decimals=12)

array([[ 1.,  0., -0.],
       [ 0.,  1., -0.],
       [-0., -0.,  1.]])