In [1]:
from itertools import product
import numpy as np

In [2]:
#  goal: take two arrays and return all pairs (i, j)

a1 = np.array([
    [0, 0, 0],
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3],
])

a2 = a1 * 2
a1, a2, a1.shape

(array([[0, 0, 0],
        [1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]]),
 array([[0, 0, 0],
        [2, 0, 0],
        [0, 4, 0],
        [0, 0, 6]]),
 (4, 3))

In [3]:
np.array(list(product(a1, -a2))).sum(axis=1).reshape([4, 4, 3])

array([[[ 0,  0,  0],
        [-2,  0,  0],
        [ 0, -4,  0],
        [ 0,  0, -6]],

       [[ 1,  0,  0],
        [-1,  0,  0],
        [ 1, -4,  0],
        [ 1,  0, -6]],

       [[ 0,  2,  0],
        [-2,  2,  0],
        [ 0, -2,  0],
        [ 0,  2, -6]],

       [[ 0,  0,  3],
        [-2,  0,  3],
        [ 0, -4,  3],
        [ 0,  0, -3]]])