In [1]:
from ase.build import supercells
from ase.io import read
from time import time
from subprocess import run
import importlib as il
import numpy as np
import os

In [2]:
# Check if LD_LIBRARY_PATH is up to date
os.getcwd() in os.environ['LD_LIBRARY_PATH'].split(':')

False

In [3]:
gao = read('geometry.in', 0, 'aims')

In [4]:
# Number of atoms
gao.get_number_of_atoms()

10

In [5]:
# Target number of atoms: 200
n_target = 220
target_size = n_target / gao.get_number_of_atoms()
print(f'Target size: {target_size:.2f}')

Target size: 22.00


In [6]:
# Python implementation
stime = time()
smatrix = supercells.find_optimal_cell_shape(gao.cell, target_size=target_size, target_shape='sc', verbose=1,
                                            lower_limit=-2, upper_limit=2)
python_time = time() - stime
print(f'..found in {python_time:.3f}s')

target metric (h_target):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
normalization factor (Q): 0.0745796
idealized transformation matrix:
[[ 1.0765228   1.0765228   0.        ]
 [-4.34988933  4.34988933  0.        ]
 [ 0.26220383  0.26220383  2.34904451]]
closest integer transformation matrix (P_0):
[[ 1  1  0]
 [-4  4  0]
 [ 0  0  2]]
smallest score (|Q P h_p - h_target|_2): 0.580774
optimal transformation matrix (P_opt):
[[ 1  1  0]
 [-5  5 -1]
 [-1  1  2]]
supercell metric:
[[12.4554  0.      0.    ]
 [ 1.3903 15.4125 -5.7081]
 [-2.7806  3.0825 11.4161]]
determinant of optimal transformation matrix: 22
..found in 23.862s


## f2py

In [7]:
import supercell as sc

In [8]:
# ?sc.supercell.find_optimal_cell

In [9]:
target_size

22.0

In [10]:
stime = time()
smatrix = sc.supercell.find_optimal_cell(gao.cell, np.eye(3), 30.)
fortran_time = time()-stime
print(f'..found in {fortran_time:.5f}s')
smatrix

..found in 0.00010s


array([[ 1,  1,  0],
       [-5,  5,  0],
       [ 0,  0,  3]], dtype=int32)

In [11]:
print(f'Speedup is {python_time / fortran_time:.3f}')

Speedup is 242927.532
