In [1]:
import numpy as np
from itertools import product

from ase.io import read
from ase.neighborlist import neighbor_list

In [2]:
supercell = read('geometry.in.supercell', format='aims')

In [3]:
def bounding_sphere_radius(cell, eps=1e-9):
    vertices = []
    for (i, j, k) in product(range(2), repeat=3):
        vec = np.array([i, j, k]) @ cell
        vertices.append(vec)
        
    # check for mutual distances
    d_max = -1
    for v1 in vertices:
        for v2 in vertices:
            d = np.linalg.norm(v1 - v2)
            if d > d_max:
                d_max = d
                
    return d_max + eps

In [4]:
cutoff = bounding_sphere_radius(supercell.cell) / 2

In [5]:
# find list of neighbors
index_i, index_j, distance_abs, distance_vec, shift_vec = neighbor_list('ijdDS', supercell, cutoff=cutoff)
len(index_i)

224

In [6]:
# sort by distance of i and distance of j
metric = np.linalg.norm(supercell.positions[index_i], axis=1) 
metric += np.linalg.norm(supercell.positions[index_j], axis=1) * .99

In [7]:
sortargs = np.argsort(metric)

In [8]:
for ii in sortargs[:10]:
    print(supercell[index_i[ii]].position, supercell[index_j[ii]].position, shift_vec[ii])

[0. 0. 0.] [1.35651688 1.35651688 1.35651688] [0 0 0]
[0. 0. 0.] [1.35651688 1.35651688 1.35651688] [-1  0  0]
[0. 0. 0.] [1.35651688 1.35651688 1.35651688] [ 0 -1  0]
[0. 0. 0.] [1.35651688 1.35651688 1.35651688] [ 0  0 -1]
[1.35651688 1.35651688 1.35651688] [0. 0. 0.] [1 0 0]
[1.35651688 1.35651688 1.35651688] [0. 0. 0.] [0 0 0]
[1.35651688 1.35651688 1.35651688] [0. 0. 0.] [0 1 0]
[1.35651688 1.35651688 1.35651688] [0. 0. 0.] [0 0 1]
[0. 0. 0.] [2.71303376 2.71303376 0.        ] [-1 -1  0]
[0. 0. 0.] [2.71303376 2.71303376 0.        ] [ 0 -1  0]
