In [17]:
import numpy as np
from ase.build import bulk
from ase.io.aims import read_aims as read

In [44]:
a1 = bulk('Al')
a2 = bulk('Al')

a2.cell[0, 0] += .5
a2.cell[0, 1] += .5
a2

Atoms(symbols='Al', pbc=True, cell=[[0.5, 2.525, 2.025], [2.025, 0.0, 2.025], [2.025, 2.025, 0.0]])

In [55]:
def deform_grad(cell1, cell2):
    return np.linalg.solve(cell1, cell2).T

In [56]:
(deform_grad(a1.cell, a2.cell) @ a1.cell).T, a2.cell[:]

(array([[5.00000000e-01, 2.52500000e+00, 2.02500000e+00],
        [2.02500000e+00, 3.25956683e-18, 2.02500000e+00],
        [2.02500000e+00, 2.02500000e+00, 0.00000000e+00]]),
 array([[0.5  , 2.525, 2.025],
        [2.025, 0.   , 2.025],
        [2.025, 2.025, 0.   ]]))

In [39]:
(a1.get_reciprocal_cell()[:] - np.linalg.inv(a1.cell).T).round(3)

array([[-0., -0., -0.],
       [-0.,  0.,  0.],
       [-0.,  0.,  0.]])

In [40]:
(a1.cell @ a1.get_reciprocal_cell()).round(2), (a1.cell @ a1.get_reciprocal_cell().T).round(2)

(array([[ 1.12, -0.12,  0.12],
        [ 0.12,  0.88, -0.12],
        [ 0.  ,  0.  ,  1.  ]]),
 array([[ 1.,  0.,  0.],
        [-0.,  1.,  0.],
        [-0.,  0.,  1.]]))

In [24]:
# cell = (rot + strain) @ fcc_cell
deform = a1.cell @ np.linalg.inv(fcc_cell)
deform

array([[ 1.00000000e+00,  6.51913366e-18,  4.93827160e-02],
       [ 6.51913366e-18,  1.00000000e+00, -6.51913366e-18],
       [ 6.51913366e-18, -6.51913366e-18,  1.00000000e+00]])

In [25]:
fcc_cell

array([[0.   , 2.025, 2.025],
       [2.025, 0.   , 2.025],
       [2.025, 2.025, 0.   ]])

In [9]:
strain = (a2.get_cell() @ a1.get_reciprocal_cell()).round(14)
strain

array([[ 1.00501733,  0.        ,  0.        ],
       [ 0.        ,  1.00501733, -0.        ],
       [ 0.        ,  0.        ,  1.00501733]])

In [24]:
a2.get_cell()[:], strain @ a1.get_cell()[:]

(array([[ 0.        ,  3.09527735,  3.09527735],
        [ 3.09527735, -0.        ,  3.09527735],
        [ 3.09527735,  3.09527735,  0.        ]]),
 array([[0.        , 3.09527735, 3.09527735],
        [3.09527735, 0.        , 3.09527735],
        [3.09527735, 3.09527735, 0.        ]]))

In [13]:
s2 = s1.copy()
s2.set_cell(strain @ s1.get_cell(), scale_atoms=True)

In [26]:
s2.cell[:], strain @ s1.cell[:]

(array([[ -3.09527735,   9.28583204,  12.38110938],
        [ -3.09527735,  12.38110938,  -9.28583204],
        [-12.38110938,  -3.09527735,  -3.09527735]]),
 array([[ -3.09527735,   9.28583204,  12.38110938],
        [ -3.09527735,  12.38110938,  -9.28583204],
        [-12.38110938,  -3.09527735,  -3.09527735]]))

In [17]:
s1.get_reciprocal_cell() @ s2.get_cell()

array([[-0.67001155,  0.0558343 , -0.72584585],
       [ 0.33500578,  0.72584585, -0.39084007],
       [ 0.33500578, -0.94918303, -0.72584585]])

In [21]:
(s1.get_cell() @ a1.get_reciprocal_cell()).round(1)

array([[ 4.,  0., -1.],
       [ 1., -4.,  3.],
       [ 1., -2., -2.]])